<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>API_AccessToken</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>7d8a5170-efc3-4358-8714-b2675999232b</testSuiteGuid>
   <testCaseLink>
      <guid>cc657560-30d2-4030-a09e-cbf43ea2388f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/REST_API_Testing/TC04_getAccessToken_Api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef8f265a-33ec-41cc-88ea-b3702c815841</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fcac161-7c8b-4319-8aba-2d54c4f50bd9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8cce562-2056-4431-9275-bab09c1bf047</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab49e535-a99c-4015-af7b-c07b0a84fe1a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5af5e678-23a6-4a9c-ad6f-483559cf3cc3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/REST_API_Testing/TC06_Access_currentUserDetail_positive_Api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86828e4c-8475-45c7-aa09-63a83884329a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9ad92343-beb6-4e1e-abb1-5d8a0f7c2f7c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d30b2848-7f7e-4dff-9452-dffacfd8397c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5551ccd0-cafd-4eb4-a3d7-8d44b2b33586</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/REST_API_Testing/TC05_RefereshAccessToken_Api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05e88791-e77b-498d-8dd0-c0afe99f1564</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ce94634-fa75-42be-803a-09d7b7a60ec9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b993fc45-35a9-4712-98c5-d185430a2510</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
