<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>API_Testcases</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>6587972d-e154-4157-bad6-7f0ddec03a0e</testSuiteGuid>
   <testCaseLink>
      <guid>8c30038f-720e-4151-bbdf-3a8f93faf451</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/REST_API_Testing/TC01_localToServer_Api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6506e230-a13c-4470-aa96-9ea0ac3c4d31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>909fef0c-4089-4bf1-97ea-6b4088d3858e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0aeda79b-6ecd-492a-906e-0105722bc177</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a6bc992-c355-42dd-b947-6710fc68d647</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31942584-6ae2-4b46-b43a-fdf58dd217ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49363e41-0e3e-4d0b-98fd-1bebc2dfb6ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6f52120a-3753-45bc-8ffa-c117a661ef54</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/REST_API_Testing/TC02_updatingCred_Api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>698a62fc-3882-4139-a2cf-accc789dbb22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>29577d49-e424-4bf5-83d7-9aa52013c995</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9228ad4a-6208-4421-bbb6-f3246b37de3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6acf17c2-9dba-453e-9706-b8c76c2abc34</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57fcd347-97f0-428a-ba32-c596b27e8455</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/REST_API_Testing/TC03_gettingCredFromServer_Api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>459c6035-e247-4f12-959f-79b9ead36462</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2896627a-57a8-43ad-8f62-861464b70c91</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fafb400-4348-40b2-b575-615f9c4f80dc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6e1dd9e-9c91-4356-8149-8043cd712687</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
