<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GraphQL_API</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>10</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9477b770-5ff0-41cd-a402-16bc7a785961</testSuiteGuid>
   <testCaseLink>
      <guid>1e47b04b-e99a-4e74-9b7d-776bbd3bd0f8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/GraphQL_API_Testing/TC01_graphql_Get_api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7dd0596-c212-42ac-81e4-6f9626ae30cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75b799ef-1c12-4709-9e8f-687ca0d00870</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0685799-ac00-4e48-a37d-1c3dd9b7f2b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14d8e91f-aa68-4c13-99b3-3efa71723e9c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51758b2b-3bb0-4178-b01b-4cab069945ec</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/GraphQL_API_Testing/TC02_graphql_Post_api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9814d6e-fec5-4e5d-9521-3cfe9b4a0bd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da1fe971-1428-4097-9c7e-6a8d9266eea6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5be4175e-910b-4481-a69b-1817a7377e04</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fab2f212-e7bd-4d35-a08e-bfa97df4d8d4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04b6e277-375e-4c6a-83b5-a027f2261d99</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/GraphQL_API_Testing/TC03_graphql_Patch_api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0903080c-49f2-47f8-975a-b0d4f1f78afe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5dd93338-269d-4cf0-b941-0bb11daf32a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>65e4af93-673b-4171-8aa8-f689bf9a2a6d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d9a1e30f-6538-4586-8d6b-1015482b125a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/API_Testing/GraphQL_API_Testing/TC04_graphql_Delete_api</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c653cdec-9ed9-4510-b401-a3eb6017abe8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d5670783-7308-4ed9-8a07-f8e870ecd457</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>77653f17-0966-4cb3-8140-39ba0d31ce66</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
