<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verifyText</name>
   <tag></tag>
   <elementGuidId>b4279b62-e8c8-43e6-ac8b-9c0bda4f58cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.page-title.my-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot; Product Returns&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f7384dcd-be37-4cab-b1cc-fdb3415fe0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-title my-3</value>
      <webElementGuid>56d4e68e-54f2-4b3e-8427-9f257898d9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Product Returns</value>
      <webElementGuid>b5a52969-5426-45fd-898e-75561fda4b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/h1[@class=&quot;page-title my-3&quot;]</value>
      <webElementGuid>4e5742a5-5c8d-40eb-8b49-a95632297586</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/h1</value>
      <webElementGuid>cb900ecd-ae6e-4f45-bcf7-97e5de1a4fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Returns'])[2]/following::h1[1]</value>
      <webElementGuid>446c0826-135e-4309-8e93-529164ab927a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SAVE60'])[1]/following::h1[1]</value>
      <webElementGuid>06c3b012-95d5-4b9b-9dd7-a81c0054cbca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue'])[1]/preceding::h1[1]</value>
      <webElementGuid>e2e796be-4df2-40cb-a40c-22bf6ce71380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Account'])[1]/preceding::h1[1]</value>
      <webElementGuid>1f00c184-e367-4594-94e9-d90ffad51457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3a3d8d9d-801d-4bfd-b0ae-be41208fb300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = ' Product Returns' or . = ' Product Returns')]</value>
      <webElementGuid>92f6b844-e478-4cb9-a93c-38ee8d3d73cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
